### PR TITLE
Underline fixes for iOS 8

### PR DESCRIPTION
**Pull request by alloy**
The fixed issue and a snapshot that shows it can be found in this commit https://github.com/artsy/Artsy-UIButtons/commit/621ef279e63b7fcdd5e61005d1c615d5132a6fb2.

Can you please tag it and push the pod release? Or otherwise grant me `pod push` powers?

### CODE REVIEW

**Comment by 1aurabrown** [comment]
it would be cool to put pods in a .gitignore because they're clogging up the diff

**Comment by alloy** [comment]
These are really the only interesting commits https://github.com/artsy/Artsy-UIButtons/commit/a2668917bf4101bf337182d5fddf8aa584aed20f & https://github.com/artsy/Artsy-UIButtons/commit/621ef279e63b7fcdd5e61005d1c615d5132a6fb2.

If you prefer that, I can remove the pods from the repo.

**Comment by orta** [comment]
Yeah, let's gitignore the `Pods/` I originally made that decision so that anyone can run the tests without a `pod install` for the cocoapods `pod lib create` template. We don't have the problem.

**Comment by alloy** [comment]
Done. It’s still a massive diff of course, so just review those 2 commits I linked to above.

**Comment by orta** [comment]
Done so, looks great, mergable on green, probably needs a `pod update` in the `.travis.yml`

**Comment by 1aurabrown** [comment]
cool, will merge. how do we grand you pod powers?

**Comment by 1aurabrown** [comment]
This image: https://github.com/artsy/Artsy-UIButtons/blob/a2668917bf4101bf337182d5fddf8aa584aed20f/Example/Tests/ReferenceImages/ARButtonSubclassesSpec/ARUnderlineButton_partially_underlines_further_in_the_title%402x.png doesn't seem to include any underline (name implies partial underline). I'm looking at it from commit https://github.com/artsy/Artsy-UIButtons/commit/a2668917bf4101bf337182d5fddf8aa584aed20f

**Comment by alloy** [comment]
Yeah that’s the failing baseline test, it’s fixed in the second commit.

**Comment by 1aurabrown** [comment]
@alloy ok thanks. have trouble seeing these things with the white on transparent

**Comment by alloy** [comment]
Oh, I just realised the ‘pod powers’ isn’t needed, we have our own spec repo for this.

**Pull request merged**
