### PR TITLE
New colors for ARNavigationTabButton & Podfile fixes

### PR DESCRIPTION
**Pull request by sarahscott**

### CODE REVIEW

**Comment by orta** [comment]
```
None of your spec sources contain a spec satisfying the dependencies: `FBSnapshotTestCase (~> 2.1.0), FBSnapshotTestCase (= 2.1.2)`.
You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

```

We'll need to do a `pod repo update` before the `pod install` here I'm afraid

**Comment by orta** [comment]
Weird, I thought you changed the Podfile reference [to FBSnapshotTestCase/Core](https://artsy.slack.com/archives/gmv-ios-dev/p1474370981001181)  - I've just re-done that, should remove swift from the equation

**Comment by orta** [comment]
That does fix the build, but you can't relay on the `pod repo update` not taking under 10m - as that failed one of the builds. I've updated the disk image to xcode 73, and will  see if that includes a later podspec for FBSnapshots and use the latest there.

**Comment by alloy** [comment]
So green! Merging 🌈

**Comment by orta** [comment]
🎉

**Pull request merged**
