### PR TITLE
Initial work on 2.0

### PR DESCRIPTION
**Pull request by orta**
Hard-codes the pod to using Artsy+UIFonts ( needed for CP 1.0 ) and migrates to using Colours 2.0

### CODE REVIEW

**Comment by ashfurrow** [comment]
Waiting on CI, it all looks good.

**Comment by ashfurrow** [comment]
Looks like it requires CocoaPods 1. I'll take a try.

**Comment by ashfurrow** [comment]
OK, with those changes we should see this green (currently failing on master).

**Comment by orta** [comment]
Cool, looks like the gemfile needs xcpretty, then should be good to go

**Comment by ashfurrow** [comment]
Looks like the problem was `FBSnapshotTestCase` now contains Swift code, and at some point we updated our use of that library, which caused the problem (we were still on Xcode 6). It's ironic that a 100% Objective-C library is _still_ impacted by Swift language changes.

**Comment by ashfurrow** [comment]
:green_apple:

**Pull request merged**
