### PR TITLE
Adds 2px corners to all buttons

### PR DESCRIPTION
**Pull request by orta**
Gives all `ARFlatButton`s a default 2px corner radius.

screen shot 2018-05-18 at 3 37 18 pm

### CODE REVIEW

**Comment by alloy** [comment]
Is this new Artsy design?

CI is red due to out of sync pods.

**Comment by orta** [comment]
Hah, I did not know this ( https://github.com/artsy/Artsy-UIButtons-artefacts/commits/master ) existed

**Comment by alloy** [comment]
Hah. Did you already check if it exists for a specific reason? Might have been a bit overkill otherwise

**Comment by orta** [comment]
At a guess, probably so that it can use the real fonts lib

**Comment by alloy** [comment]
Ohhh, yeah that makes sense

**Comment by orta** [comment]
Green, okkk

**Pull request merged**
